name 'slack_speak'
maintainer 'Tony Fruzza'
maintainer_email 'tfruzza@onica.com'
license 'MIT'
description 'Installs/Configures slack_speak'
long_description 'Installs/Configures slack_speak'
source_url 'https://github.com/tonyfruzza/slack_speak'
version '0.1.7'

depends 'aws', '~> 7.3'
